include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.2/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.2/gitlab-vm-archlinux-build-template.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.3/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.3/gitlab-vm-archlinux-build-template.yml'

default:
  tags:
    - vm
