#!/bin/sh

DIR=$1
DISTRO=$2
if [ -n "$3" ]; then
    PKGLISTFILE="$3"
else
    PKGLISTFILE="build-pkgs-base.list"
fi

set -e
if [ "$VERBOSE" -ge 2 -o "$DEBUG" == "1" ]; then
    set -x
fi

INITIAL=

if ! [ -d $DIR/home/user ]; then
    INITIAL=1
    mkdir -p $DIR

    mkdir -p $CACHEDIR/mnt_archlinux_dvd
    export INSTALLDIR=$DIR
    export SCRIPTSDIR=${ARCHLINUX_PLUGIN_DIR}scripts_archlinux/

    ${SCRIPTSDIR}/00_prepare.sh

    ${SCRIPTSDIR}/01_install_core.sh

    sudo mount $CACHEDIR/airootfs.img $CACHEDIR/mnt_archlinux_dvd

    echo "Fix bug intruduced in arch-chroot causing arguments not to be passed"
    sed "s/unshare --fork --pid//" -i $CACHEDIR/mnt_archlinux_dvd/usr/bin/arch-chroot

    cp /etc/resolv.conf $DIR/etc/

    [ -n "$SUDO_UID" ] && USER_OPTS="-u $SUDO_UID"
    [ -n "$USER_UID" ] && USER_OPTS="-u $USER_UID"
    if [ -n "$USER_GID" ]; then
        chroot $DIR groupadd -g $USER_GID user
    elif [ -n "$SUDO_GID" ]; then
        chroot $DIR groupadd -g $SUDO_GID user
    else
        chroot $DIR groupadd user
    fi
    #cd dev; /sbin/MAKEDEV generic loop;
    chroot $DIR sh -c "useradd -g user -G wheel $USER_OPTS -m user;su -c 'mkdir qubes-src' - user"

    # Install required makepkg dependencies
    sudo $CACHEDIR/mnt_archlinux_dvd/usr/bin/arch-chroot $INSTALLDIR sh -c "pacman -Sy --needed --noconfirm --asdeps binutils fakeroot sudo" 

    sudo umount $CACHEDIR/mnt_archlinux_dvd

    # Fixup so that the user can sudo without password
    sudo sh -c "echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> $INSTALLDIR/etc/sudoers.d/qubes-build-user"

    # Note: Enable x86 repos
    sudo tee -a $INSTALLDIR/etc/pacman.conf <<EOF
[multilib]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist
EOF

    # Register custom repository (it will be created later)
    sudo tee -a $INSTALLDIR/etc/pacman.conf <<EOF
[qubes]
SigLevel = Optional TrustAll
Server = file:///tmp/qubes-pkgs-mirror-repo/pkgs
EOF

fi

